# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service_manager.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15service_manager.proto\"&\n\x0eServiceRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\"!\n\x0fServiceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"$\n\rSearchRequest\x12\x13\n\x0bsearch_term\x18\x01 \x01(\t\")\n\x0eSearchResponse\x12\x17\n\x0f\x63ontainer_names\x18\x01 \x03(\t2\xdc\x01\n\x0eServiceManager\x12\x33\n\x0eRestartService\x12\x0f.ServiceRequest\x1a\x10.ServiceResponse\x12\x31\n\x0cStartService\x12\x0f.ServiceRequest\x1a\x10.ServiceResponse\x12\x30\n\x0bStopService\x12\x0f.ServiceRequest\x1a\x10.ServiceResponse\x12\x30\n\rSearchService\x12\x0e.SearchRequest\x1a\x0f.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICEREQUEST']._serialized_start=25
  _globals['_SERVICEREQUEST']._serialized_end=63
  _globals['_SERVICERESPONSE']._serialized_start=65
  _globals['_SERVICERESPONSE']._serialized_end=98
  _globals['_SEARCHREQUEST']._serialized_start=100
  _globals['_SEARCHREQUEST']._serialized_end=136
  _globals['_SEARCHRESPONSE']._serialized_start=138
  _globals['_SEARCHRESPONSE']._serialized_end=179
  _globals['_SERVICEMANAGER']._serialized_start=182
  _globals['_SERVICEMANAGER']._serialized_end=402
# @@protoc_insertion_point(module_scope)
