# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_manager_pb2 as service__manager__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RestartService = channel.unary_unary(
                '/ServiceManager/RestartService',
                request_serializer=service__manager__pb2.ServiceRequest.SerializeToString,
                response_deserializer=service__manager__pb2.ServiceResponse.FromString,
                _registered_method=True)
        self.StartService = channel.unary_unary(
                '/ServiceManager/StartService',
                request_serializer=service__manager__pb2.ServiceRequest.SerializeToString,
                response_deserializer=service__manager__pb2.ServiceResponse.FromString,
                _registered_method=True)
        self.StopService = channel.unary_unary(
                '/ServiceManager/StopService',
                request_serializer=service__manager__pb2.ServiceRequest.SerializeToString,
                response_deserializer=service__manager__pb2.ServiceResponse.FromString,
                _registered_method=True)
        self.SearchService = channel.unary_unary(
                '/ServiceManager/SearchService',
                request_serializer=service__manager__pb2.SearchRequest.SerializeToString,
                response_deserializer=service__manager__pb2.SearchResponse.FromString,
                _registered_method=True)


class ServiceManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RestartService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RestartService': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartService,
                    request_deserializer=service__manager__pb2.ServiceRequest.FromString,
                    response_serializer=service__manager__pb2.ServiceResponse.SerializeToString,
            ),
            'StartService': grpc.unary_unary_rpc_method_handler(
                    servicer.StartService,
                    request_deserializer=service__manager__pb2.ServiceRequest.FromString,
                    response_serializer=service__manager__pb2.ServiceResponse.SerializeToString,
            ),
            'StopService': grpc.unary_unary_rpc_method_handler(
                    servicer.StopService,
                    request_deserializer=service__manager__pb2.ServiceRequest.FromString,
                    response_serializer=service__manager__pb2.ServiceResponse.SerializeToString,
            ),
            'SearchService': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchService,
                    request_deserializer=service__manager__pb2.SearchRequest.FromString,
                    response_serializer=service__manager__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServiceManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ServiceManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RestartService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceManager/RestartService',
            service__manager__pb2.ServiceRequest.SerializeToString,
            service__manager__pb2.ServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceManager/StartService',
            service__manager__pb2.ServiceRequest.SerializeToString,
            service__manager__pb2.ServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceManager/StopService',
            service__manager__pb2.ServiceRequest.SerializeToString,
            service__manager__pb2.ServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceManager/SearchService',
            service__manager__pb2.SearchRequest.SerializeToString,
            service__manager__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
